### ISSUE TITLE
Upload to Forge

### ISSUE THREAD

**Issue by laurivosandi** [jlyheden/puppet-pam#4]
Hi, please upload the module to Puppet Forge :)

**Comment by jlyheden** [comment]
Hi, this module hasn't received much love in some time. I'll see if it is easily possible to get all tests to pass without too much of a rewrite and then push it to the forge.

**Comment by jlyheden** [comment]
I've prepped the module for upload but my forge account password seem to be invalid and the password reset feature is currently broken in forge.puppetlabs.com. Waiting for PL to fix it :)

**Comment by jlyheden** [comment]
Uploaded to https://forge.puppetlabs.com/jpl/pam
